### ISSUE TITLE
--head https://

### ISSUE THREAD

**Issue by xudonymous** [alexwitherspoon/plexhealthcheck#2]
Hey, thanks for the script! It works perfectly as an http request to Plex. However, I have Cloudbox setup so Sonarr/Radarr/Ombi/etc. use https to access. What's the best way to edit the script to compensate?

**Comment by alexwitherspoon** [comment]
I missed the alert on this, I've created a PR to test this change: https://github.com/alexwitherspoon/plexhealthcheck/pull/3

**Comment by alexwitherspoon** [comment]
Merged some changes, give that a try.
